### ISSUE TITLE
Error during npm run build : node-sass not found

### ISSUE THREAD

**Issue by rroblik** [LINKIWI/linkr#14]
Hi,

I'm following the installation guide on the main page. All is ok until the 
`NODE_ENV=production npm run build` command

Here is the (begin of) the output  : 
```
$ NODE_ENV=production npm run build

> linkr@1.0.0 build /mnt/hgfs/_wprojects/linkr
> npm run generate-secret && npm run build-css && npm run build-js && npm run build-html


> linkr@1.0.0 generate-secret /mnt/hgfs/_wprojects/linkr
> PYTHONPATH=. python scripts/generate_secret.py

Secret already exists on disk; skipping.

> linkr@1.0.0 build-css /mnt/hgfs/_wprojects/linkr
> mkdir -p frontend/static/dist && node-sass --output-style compressed frontend/styles/main.scss frontend/static/dist/main.css

sh: 1: node-sass: not found

```

Here is the `npm-debug.log` file
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/deuser/.nvm/versions/node/v6.12.2/bin/node',
1 verbose cli   '/home/deuser/.nvm/versions/node/v6.12.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.12.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle linkr@1.0.0~prebuild: linkr@1.0.0
6 silly lifecycle linkr@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle linkr@1.0.0~build: linkr@1.0.0
8 verbose lifecycle linkr@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle linkr@1.0.0~build: PATH: /home/deuser/.nvm/versions/node/v6.12.2/lib/node_modules/npm/bin/node-gyp-bin:/mnt/hgfs/_wprojects/linkr/node_modules/.bin:/home/deuser/.nvm/versions/node/v6.12.2/bin:/home/deuser/.composer/vendor/bin:/home/deuser/Envs/linkr/bin:/home/deuser/.npm-global/bin:/home/deuser/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle linkr@1.0.0~build: CWD: /mnt/hgfs/_wprojects/linkr
11 silly lifecycle linkr@1.0.0~build: Args: [ '-c',
11 silly lifecycle   'npm run generate-secret && npm run build-css && npm run build-js && npm run build-html' ]
12 silly lifecycle linkr@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle linkr@1.0.0~build: Failed to exec build script
14 verbose stack Error: linkr@1.0.0 build: `npm run generate-secret && npm run build-css && npm run build-js && npm run build-html`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/deuser/.nvm/versions/node/v6.12.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/deuser/.nvm/versions/node/v6.12.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid linkr@1.0.0
16 verbose cwd /mnt/hgfs/_wprojects/linkr
17 error Linux 3.16.0-4-amd64
18 error argv "/home/deuser/.nvm/versions/node/v6.12.2/bin/node" "/home/deuser/.nvm/versions/node/v6.12.2/bin/npm" "run" "build"
19 error node v6.12.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error linkr@1.0.0 build: `npm run generate-secret && npm run build-css && npm run build-js && npm run build-html`
22 error Exit status 1
23 error Failed at the linkr@1.0.0 build script 'npm run generate-secret && npm run build-css && npm run build-js && npm run build-html'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the linkr package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run generate-secret && npm run build-css && npm run build-js && npm run build-html
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs linkr
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls linkr
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Problem with `node-sass` I think but I don't understand why. Here is the `node-sass version` :

```
$ node -p "require('node-sass').info"
node-sass       4.7.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

Regards

**Comment by LINKIWI** [comment]
Sorry, I didn't see this issue until just now. Can you clear node_modules and paste the output of `npm install`? Either dev dependencies aren't being installed, or the SASS binaries aren't being built properly.
